######################################################################
# Automatically generated by qmake (3.0) Tue Nov 18 06:55:10 2014
######################################################################

TEMPLATE = app
TARGET = byteConverter
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += ByteConverterDialog.h
SOURCES += main.cpp ByteConverterDialog.cpp
