//with this program prototype I am trying to take a list of input words, count the length of each word (assuming that the ' ' separates words), and create an array of the lengths based off of the number of words that are input.of
//with the final program, I want to take the array generated by the prototype and convert it to a vertical Hisotgram using underlines to represent the characters of each word.  The dimensions of the histogram will be (# of words) x (character length of longest word)

#include <stdio.h>
#include <stdlib.h>

#define IN 1
#define OUT 0
#define MAXLENGTH 50

int wordlength(char word[], int maxlength);
void copy(char to[], char from[]);
int wordcount();

int main(){
    int len;
    int wordcount1 = wordcount();
//    int wlength[wordcount1];
    char word[MAXLENGTH];
    int i;
    
    i = 0;
    
    while ((len = wordlength(word, MAXLENGTH) > 0)){
           printf("%d \n", len);
        }
    
    printf("%d \n", wordcount1);
    
//    int j;
//    for(j = 0; j < wordcount1; j++) {
//        printf("%d \n", wlength[j]);
//               }
    
    return 0;
}


int wordlength(char s[], int lim){
    
    int c, i;
    
    for (i=0; i<lim-1 && (c=getchar()) != EOF && c != ' '; ++i)
        s[i] = c;
    if (c == ' ') {
        s[i] = c;
        ++i;
    }
    s[i] = '\0';
    return i;
}

void copy(char to[], char from[]){
    
    int i;
    
    i = 0;
    while ((to[i] = from[i]) != '\0')
        ++i;
}

int wordcount(){
    int c, nw, state;
    
    state = OUT;
    nw = 0;
    while ((c = getchar()) != EOF) {
        if (c == ' ' || c == '\n' || c == '\t'){
            state = OUT;
        }
        else {
            if (state == OUT) {
                state = IN;
                ++nw;
            }
        }
    }
    return nw;
}




//    int len;
//    int max;
//    char word[MAXLENGTH];
//    char longest[MAXLENGTH];
//
//    max = 0;
//    while ((len = wordlength(word, MAXLENGTH)) > 0)
//        if (len > max) {
//            max = len;
//            copy(longest, word);
//        }
//    if (max > 0)
//        printf("%s \n", longest);
//    return 0;

//int wc[3]{
//	int c, nl, nw, nc, state;
//
//	state = OUT;
//	n1 = nw = nc = 0;
//	while ((c = getchar()) != EOF) {
//		++nc;
//		if (c == '\n'){
//			++nl;
//			}
//		if (c == ' ' || c == '\n' || c == '\t'){
//			state = OUT;
//			}
//		else {
//			if (state == OUT) {
//				state = IN;
//				++nw;
//				}
//			}
//		}
//	wc[1] = nl;
//	wc[2] = nw;
//	wc[3] = nc;
//	}
	

	