######################################################################
# Automatically generated by qmake (3.0) Sun Nov 16 12:42:02 2014
######################################################################

TEMPLATE = app
TARGET = qtconverter
INCLUDEPATH += .
QT += widgets
#LIBS +=

# Input
HEADERS += Summer.h
SOURCES += qtconverter.cpp
