######################################################################
# Automatically generated by qmake (3.0) Sun Nov 16 23:07:58 2014
######################################################################

TEMPLATE = app
TARGET = DesignerTest
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += DesignerTest.h Summer.h
FORMS += DesignerTest.ui
SOURCES += mainDesigner.cpp
