######################################################################
# Automatically generated by qmake (3.0) Thu Oct 9 10:20:16 2014
######################################################################

TEMPLATE = app
TARGET = age
INCLUDEPATH += .

# Input
SOURCES += age.cpp
QT += widgets
