######################################################################
# Automatically generated by qmake (3.0) Thu Oct 9 09:52:08 2014
######################################################################

TEMPLATE = app
TARGET = quit
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
QT += widgets
