######################################################################
# Automatically generated by qmake (3.0) Wed Dec 10 15:52:02 2014
######################################################################

TEMPLATE = app
TARGET = byteConverter2
INCLUDEPATH += .

# Input
HEADERS += ByteConverter.h ByteConverterDialog.h
SOURCES += ByteConverter.cpp ByteConverterDialog.cpp
